const MAYORS = {
  'Paris':             { name: 'Anne Hidalgo',            wiki: 'Anne_Hidalgo' },
  'Marseille':         { name: 'Benoît Payan',             wiki: 'Benoît_Payan' },
  'Lyon':              { name: 'Grégory Doucet',           wiki: 'Grégory_Doucet' },
  'Toulouse':          { name: 'Jean-Luc Moudenc',         wiki: 'Jean-Luc_Moudenc' },
  'Nice':              { name: 'Christian Estrosi',        wiki: 'Christian_Estrosi' },
  'Nantes':            { name: 'Johanna Rolland',          wiki: 'Johanna_Rolland' },
  'Strasbourg':        { name: 'Jeanne Barseghian',        wiki: 'Jeanne_Barseghian' },
  'Bordeaux':          { name: 'Pierre Hurmic',            wiki: 'Pierre_Hurmic' },
  'Lille':             { name: 'Martine Aubry',            wiki: 'Martine_Aubry' },
  'Rennes':            { name: 'Nathalie Appéré',          wiki: 'Nathalie_Appéré' },
  'Reims':             { name: 'Arnaud Robinet',           wiki: 'Arnaud_Robinet' },
  'Saint-Étienne':     { name: 'Gaël Perdriau',            wiki: 'Gaël_Perdriau' },
  'Toulon':            { name: 'Hubert Falco',             wiki: 'Hubert_Falco' },
  'Le Havre':          { name: 'Édouard Philippe',         wiki: 'Édouard_Philippe' },
  'Grenoble':          { name: 'Éric Piolle',              wiki: 'Éric_Piolle' },
  'Dijon':             { name: 'François Rebsamen',        wiki: 'François_Rebsamen' },
  'Angers':            { name: 'Jean-Marc Verchère',       wiki: 'Jean-Marc_Verchère' },
  'Nîmes':             { name: 'Jean-Paul Fournier',       wiki: 'Jean-Paul_Fournier_(homme_politique)' },
  'Villeurbanne':      { name: 'Cédric Van Styvendael',    wiki: 'Cédric_Van_Styvendael' },
  'Le Mans':           { name: 'Marietta Karamanli',       wiki: 'Marietta_Karamanli' },
  'Clermont-Ferrand':  { name: 'Olivier Bianchi',          wiki: 'Olivier_Bianchi_(homme_politique)' },
  'Brest':             { name: 'François Cuillandre',      wiki: 'François_Cuillandre' },
  'Tours':             { name: 'Emmanuel Denis',           wiki: 'Emmanuel_Denis_(homme_politique)' },
  'Amiens':            { name: 'Brigitte Fouré',           wiki: 'Brigitte_Fouré' },
  'Limoges':           { name: 'Émile-Roger Lombertie',    wiki: 'Émile-Roger_Lombertie' },
  'Perpignan':         { name: 'Louis Aliot',              wiki: 'Louis_Aliot' },
  'Metz':              { name: 'François Grosdidier',      wiki: 'François_Grosdidier' },
  'Besançon':          { name: 'Anne Vignot',              wiki: 'Anne_Vignot' },
  'Caen':              { name: 'Joël Bruneau',             wiki: 'Joël_Bruneau' },
  'Orléans':           { name: 'Serge Grouard',            wiki: 'Serge_Grouard' },
  'Rouen':             { name: 'Nicolas Mayer-Rossignol',  wiki: 'Nicolas_Mayer-Rossignol' },
  'Mulhouse':          { name: 'Michèle Lutz',             wiki: 'Michèle_Lutz' },
  'Montpellier':       { name: 'Michaël Delafosse',        wiki: 'Michaël_Delafosse' },
  'Nancy':             { name: 'Mathieu Klein',            wiki: 'Mathieu_Klein' },
  'Avignon':           { name: 'Cécile Helle',             wiki: 'Cécile_Helle' },
  'Poitiers':          { name: 'Léonore Moncond\'huy',     wiki: 'Léonore_Moncond\'huy' },
  'Pau':               { name: 'François Bayrou',          wiki: 'François_Bayrou' },
  'La Rochelle':       { name: 'Jean-François Fountaine',  wiki: 'Jean-François_Fountaine' },
  'Calais':            { name: 'Natacha Bouchart',         wiki: 'Natacha_Bouchart' },
  'Bayonne':           { name: 'Jean-René Etchegaray',     wiki: 'Jean-René_Etchegaray' },
}

export default MAYORS
